Resources:
  BlackjackBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.bucketName}
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  S3AccessPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: BlackjackBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: arn:aws:s3:::${self:custom.bucketName}/*