org: vesnathan
app: blackjack
service: blackjack

provider:
  name: aws
  runtime: nodejs16.x
  profile: blackjackUser
  region: ap-southeast-2
  stage: ${opt:stage}
  httpApi:
    cors: true

plugins:
  - serverless-s3-sync
  - serverless-appsync-plugin
  - serverless-webpack
  - serverless-cloudfront-invalidate

package:
  individually: true
  exclude:
    - ./node_modules/**
    - node_modules/**

custom:
  cloudfrontInvalidate:
    - distributionIdKey: CDNDistributionId
      items:
        - "/index.html"
        - "/manifest*"
        - "/static*"
  bucketName: blackjack-o5z9dq1v9p
  s3Sync:
    - bucketName: ${self:custom.bucketName}-${opt:stage}
      localDir: ../client/build/
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
  appSync:
    name: blackjack-appsync-api
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: ap-southeast-2
      defaultAction: ALLOW
      userPoolId: !Ref cognitoUserPool
    mappintTemplatesLocation: mapping-templates
    mappingTemplates: 
      - type: Mutation
        field: saveGame
        dataSource: gamesTable
      - type: Mutation
        field: loadGame
        dataSource: gamesTable
    dataSources: 
      - type: AMAZON_DYNAMODB
        name: gamesTable
        config:
          tableName: !Ref gamesTable

    

resources:
  -  Resources:
  -  ${file(./resources/DynamoDb/dynamoDb.yaml)}
  -  ${file(./resources/Cognito/cognito.yaml)}
  -  ${file(./resources/S3/s3.yaml)}
  -  ${file(./resources/Cloudfront/cloudfront.yaml)}
  -  ${file(./resources/CloudWatch/CloudWatch.yaml)}
	
functions:
  preSignUp:
    handler: handler.autoConfirmUser
    events:
      - cognitoUserPool:
          pool: blackjackUserPool-${opt:stage}
          trigger: PreSignUp
          existing: true
  stripePaymentIntent:
    handler: handler.getStripePaymentIntent
    events:
      - http:
          path: getStripePaymentIntent
          method: post
          cors: true
    environment:
      STRIPE_SECRET_KEY:  ${param:STRIPE_SK}

Outputs:
  stripePaymentIntent:
    Value: !GetAtt stripePaymentIntent.Arn
    Export:
      Name: stripePaymentIntentArn

  cognitoUserPoolId:
    Value: !Ref cognitoUserPool
    Export:
      Name: cognitoUserPoolId

  cognitoUserPoolClientId:
    Value: !Ref cognitoUserPoolClient
    Export:
      Name: cognitoUserPoolClientId

  cognitoAdminGroup:
    Value: !Ref cognitoAdminGroup
    Export:
      Name: cognitoAdminGroup

  cognitoAdminIAMRole:
    Value: !GetAtt cognitoAdminIAMRole.Arn
    Export:
      Name: cognitoAdminIAMRole

  cognitoCustomerGroup:
    Value: !Ref cognitoCustomerGroup
    Export:
      Name: cognitoCustomerGroup

  cognitoUserIAMRole:
    Value: !GetAtt cognitoUserIAMRole.Arn
    Export:
      Name: cognitoUserIAMRole

  gamesTable:
    Value: !Ref gamesTable
    Export:
      Name: gamesTable

  gamesTableArn:
    Value: !GetAtt gamesTable.Arn
    Export:
      Name: gamesTableArn

  gamesTableStreamArn:
    Value: !GetAtt gamesTable.StreamArn
    Export:
      Name: gamesTableStreamArn

  gamesTableStreamName:
    Value: !GetAtt gamesTable.StreamArn
    Export:
      Name: gamesTableStreamName

        

