Resources:
  cognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UsernameAttributes:
        - email
      UserPoolName: "blackjackUserPool-${opt:stage}"

  cognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: Web-${opt:stage}
      UserPoolId: !Ref cognitoUserPool

  cognitoAdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: "Admin User Group"
      GroupName: "Admin-${opt:stage}"
      Precedence: 0
      RoleArn: !GetAtt cognitoAdminIAMRole.Arn
      UserPoolId: !Ref cognitoUserPool

  cognitoAdminIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                - "cognito-identity.amazonaws.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition: {
              StringEquals: {
                "cognito-identity.amazonaws.com:aud": !Ref cognitoUserPool
              },
            }
      Description: "Admin Role"
      Policies:
        - PolicyName: "blackjack-admin-group-policy-${opt:stage}"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:*"
                Resource: 
                  - !GetAtt gamesTable.Arn
      RoleName: "blackjack-admin-role-${opt:stage}"

  cognitoCustomerGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: "Customer User Group"
      GroupName: "Customer-${opt:stage}"
      Precedence: 1
      RoleArn: !GetAtt cognitoUserIAMRole.Arn
      UserPoolId: !Ref cognitoUserPool

  cognitoUserIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "blackjack-customer-role-${opt:stage}"
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                - "cognito-identity.amazonaws.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition: {
              StringEquals: {
                "cognito-identity.amazonaws.com:aud": !Ref cognitoUserPool
              },
            }
      Description: "User Role"
      Policies:
        - PolicyName: "blackjack-customer-group-policy-${opt:stage}"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:GetItem"
                  - "dynamodb:PutItem"
                Resource:
                  - !GetAtt gamesTable.Arn

                 

                  