export const AWS_USER_POOL_ID = "ap-southeast-2_y1OSue9QA"
export const AWS_CLIENT_ID = "3j3fbjpvkn601tnr430lkaaejg"
export const AWS_REGION = "ap-southeast-2"
export const GRAPHQL_URL = "https://harsffx2o5f77baaskhajx3gpe.appsync-api.ap-southeast-2.amazonaws.com/graphql"
export const GET_PAYMENT_INTENT_URL = "https://2tmuftuqzg.execute-api.ap-southeast-2.amazonaws.com/dev/getStripePaymentIntent"
export const AWS_CLOUDFRONT_URL = "https://d3ezb6hxr7udjr.cloudfront.net"
