export const AWS_USER_POOL_ID = "ap-southeast-2_e2Xw7EPXm"
export const AWS_CLIENT_ID = "5nei6q6fh1076crjhnkovngku1"
export const AWS_REGION = "ap-southeast-2"
export const GRAPHQL_URL = "https://jobtdp6w3bakzabmsqeykx4jri.appsync-api.ap-southeast-2.amazonaws.com/graphql"
export const GET_PAYMENT_INTENT_URL = "https://yg09x4ddi1.execute-api.ap-southeast-2.amazonaws.com/dev/getStripePaymentIntent"
export const AWS_CLOUDFRONT_URL = "https://dbnyvrrc1jvyf.cloudfront.net/"
