Resources:
  gamesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: "userId"
          KeyType: "HASH"
      Tags:
        - Key: Name 
          Value: games-table